// Copyright 2009 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


// This file will be processed by the MIDL tool to produce the type library
// and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
  object,
  uuid(B0608AA2-3C43-424B-9814-5A9DFF06AABE),
  dual,
  nonextensible,
  helpstring("IPersistentOptOutBHO Interface"),
  pointer_default(unique)
]
interface IPersistentOptOutBHO : IDispatch{ };

[
  uuid(F240BFEF-88DD-4F6D-9816-D32E509B929B),
  version(1.0),
  helpstring("PersistentOptOut 1.0 Type Library")
]
library PersistentOptOutLib
{
  importlib("stdole2.tlb");
  [
    uuid(8E425EB4-ADBD-4816-B1E8-49BB9DECF034),
    helpstring("PersistentOptOutBHO Class")
  ]
  coclass PersistentOptOutBHO {
    [default] interface IPersistentOptOutBHO;
  };
};
